#!/bin/bash

# Configuration for client rule.
# ipv4 client only
# By default allows all connections out
# And only established connections back.

TARGET="ACCEPT"
PORT=
CTSTATE="RELATED,ESTABLISHED"
PROTOCOL="tcp"
DCHAIN="OUTPUT"
CHAIN="INPUT"
DEST=
SRC=

# IPv6 defaults
TARGET_6=
POST_6=
CTSTATE_6="RELATED,ESTABLISHED"
PROTOCOL_6="tcp"
DCHAIN_6="OUTPUT"
CHAIN_6="INPUT"
DEST_6=
SRC_6=
