#!/bin/bash

# Configuration for client rule.
# ipv4 client only
# By default allows all connections out
# And only established connections back.

TARGET="ACCEPT"
PORT=
CTSTATE="RELATED,ESTABLISHED"
PROTOCOL=
DCHAIN="FORWARD"
CHAIN="FORWARD"
DEST=
SRC=

TARGET_6=
PORT_6=
CTSTATE_6="RELATED,ESTABLISHED"
PROTOCOL_6=
DCHAIN_6="FORWARD"
CHAIN_6="FORWARD"
DEST_6=
SRC_6=
