#!/bin/bash

# Configuration for client rule.
# ipv4 client only
# By default allows all connections out
# And only established connections back.

PORT=
CTSTATE="RELATED,ESTABLISHED"
PROTOCOL=
TARGET="ACCEPT"
DCHAIN="FORWARD"
CHAIN="FORWARD"
DEST=
SRC=
