#!/bin/bash

# Configuration for interface rules

IF="lo"
TARGET="ACCEPT"

# Specify input/output chains.
# Leave blank to exclude.
# CHAINS_IN=CHAIN="INPUT FORWARD PREROUTING"
# CHAINS_OUT=DCHAIN="OUTPUT FORWARD POSTROUTING"

DCHAIN="INPUT"
DCHAIN_6="INPUT"

CHAIN="OUTPUT"
CHAIN_6="OUTPUT"
