#!/bin/bash

# Configuration for interface rules

IF="lo"
OF="lo"
IF_6="lo"
OF_6="lo"
TARGET="ACCEPT"
TARGET_6="ACCEPT"

# Specify input/output chains.
# Leave blank to exclude.
# CHAINS_IN=CHAIN="INPUT FORWARD PREROUTING"
# CHAINS_OUT=DCHAIN="OUTPUT FORWARD POSTROUTING"

CHAIN="INPUT"
CHAIN_6="INPUT"

DCHAIN="OUTPUT"
DCHAIN_6="OUTPUT"
