#!/bin/bash

# Configuration for client rule.
# ipv4 client only
# By default allows all connections out
# And only established connections back.

TARGET="ACCEPT"
PORT=
CTSTATE=""
PROTOCOL="tcp"
DCHAIN="INPUT"
CHAIN="OUTPUT"
DEST=
SRC=

TARGET_6=
PORT_6=
CTSTATE_6=""
PROTOCOL_6="tcp"
DCHAIN_6="INPUT"
CHAIN_6="OUTPUT"
DEST_6=
SRC_6=
