#!/bin/bash

# A template for init conf files.

# PORT=  port
# SRC=  source ip subnet
# DEST=  destination ip subnet
# CTSTATE=  connection tracking state
# PROTOCOL=  protocol
# IF=  interface

# TARGET= jump target
# LOG= Logging on/off (not implemented)
# VERBOSE= Verbosity on/off (not implemented)

# POLICY[$CHAIN]= Default policy for chain
# JUMP[$IF]= Default jump policy for interface
# JUMP[$CHAIN]= Default jump policy for chain
# FINAL_JUMP[$CHAIN]= Default final_jump for chain

# For ipv6, suffix with "_6"
# For example
# PORT_6=80

# These values should not be overridden by this conf file.
# ( Global variables defined by init.d/env )
# ENV
# CONF_VARS
# DIR_BASE
# CONF_BASE
# ENV_BASE
# IPTABLES
# IPTABLES_6
# TABLES
# DEFAULT_CHAINS
# SUBNET
# LOCAL
# GATEWAY
# MASQ_IN
# MASQ_OUT
# PING_REQUEST
# PING_REPLY
