#!/bin/bash

# A template for creating init scripts for iptables.
ENV_FILE=`dirname "$(dirname \
					 "$(readlink -e "$0" )")"`/init.d/env
source "${ENV_FILE}" "$@" || exit 1

# Empty arrays
RULES=()
RULES_TGT=()

# Execute function
$@
