#!/bin/bash

# A template for creating init scripts for iptables.
ENV_FILE=`dirname "$(dirname \
					 "$(readlink -e "$0" )")"`/init.d/env
source "${ENV_FILE}" "$@" || exit 1

# Empty arrays
RULES=()
RULES_TGT=()

# target
# Only create rules if a target is specified.

i=0
# IPv4 rules
if [[ -n $TARGET ]];
	 then
		 # Optional singular arguments
		 # Output interface
		 [[ -n $OF ]] &&
			 xIF="-i $OF" &&
			 OF="-o $OF"

		 # Input interface (FORWARD chains only)
		 [[ -n $IF ]] &&
			 xOF="-o $IF" &&
			 IF="-i $IF"

		 # protocol
		 [[ -n $PROTOCOL ]] && PROTOCOL="-p $PROTOCOL"

		 # ctstate
		 [[ -n $CTSTATE ]] && CTSTATE="-m conntrack --ctstate $CTSTATE"

		 # Address restrictions
		 [[ -n $DEST ]] &&
			 xSRC="-s $DEST" &&
			 DEST="-d $DEST"

		 [[ -n $SRC ]] &&
			 xDEST="-d $SRC" &&
			 SRC="-s $SRC"

		 # Just specify destination port
		 # with respect to client
		 [[ -n $PORT ]] &&
			 dport="--dport $PORT" &&
			 xsport="--sport $PORT" &&
			 xdport= && sport=

		 # Specify source port and destination port
		 # OVERRIDES PORT
		 # with respect to client
		 [[ -n $DPORT ]] &&
			 dport="--dport ${DPORT}" &&
			 xsport="--sport ${DPORT}"
		 [[ -n $SPORT ]] &&
			 xdport="--dport ${SPORT}" &&
			 sport="--sport ${SPORT}"

		 # OUTPUT
		 RULES[$i]="$DCHAIN $IF $OF $PROTOCOL ${SRC} ${DEST} $sport $dport"
		 RULES_TGT[$i]="-j $TARGET"
		 (( i++ ))

		 # RETURN
		 RULES[$i]="$CHAIN $xIF $xOF $PROTOCOL $CTSTATE ${xDEST} ${xSRC} $xsport $xdport"
		 RULES_TGT[$i]="-j $TARGET"
		 (( i++ ))
fi

if [[ -n $TARGET_6 ]];
	 then
		 # Optional singular arguments
		 # Output interface
		 [[ -n $OF_6 ]] &&
			 xIF_6="-i $OF_6" &&
			 OF_6="-o $OF_6"

		 # Input interface (FORWARD chains only)
		 [[ -n $IF_6 ]] &&
			 xOF_6="-o $IF_6" &&
			 IF_6="-i $IF_6"

		 # protocol
		 [[ -n $PROTOCOL_6 ]] && PROTOCOL_6="-p $PROTOCOL_6"

		 # ctstate
		 [[ -n $CTSTATE_6 ]] && CTSTATE_6="-m conntrack --ctstate $CTSTATE_6"

		 # Address restrictions
		 [[ -n $DEST_6 ]] &&
			 xSRC_6="-s $DEST_6" &&
			 DEST_6="-d $DEST_6"

		 [[ -n $SRC_6 ]] &&
			 xDEST_6="-d $SRC_6" &&
			 SRC_6="-s $SRC_6"

		 # Just specify destination port
		 # with respect to client
		 [[ -n $PORT_6 ]] &&
			 dport_6="--dport $PORT_6" &&
			 xsport_6="--sport $PORT_6" &&
			 xdport_6= && sport_6=

		 # Specify source port and destination port
		 # OVERRIDES PORT
		 # with respect to client
		 [[ -n $DPORT_6 ]] &&
			 dport_6="--dport ${DPORT_6}" &&
			 xsport_6="--sport ${DPORT_6}"
		 [[ -n $SPORT_6 ]] &&
			 xdport_6="--dport ${SPORT_6}" &&
			 sport_6="--sport ${SPORT_6}"

		 # OUTPUT
		 RULES[$i]="6 $DCHAIN_6 $IF_6 $OF_6 $PROTOCOL_6 ${SRC_6} ${DEST_6} $sport_6 $dport_6"
		 RULES_TGT[$i]="-j ${TARGET_6}"
		 (( i++ ))

		 # RETURN
		 RULES[$i]="6 $CHAIN_6 $xIF_6 $xOF_6 $PROTOCOL_6 $CTSTATE_6 ${xDEST_6} ${xSRC_6} $xsport_6 $xdport_6"
		 RULES_TGT[$i]="-j ${TARGET_6}"
		 (( i++ ))
fi

# Execute function
$1
