#!/bin/bash

# A template for creating init scripts for iptables.
ENV_FILE=`dirname "$(dirname \
					 "$(readlink -e "$0" )")"`/init.d/env
source "${ENV_FILE}" "$@" || exit 1

# Empty arrays
RULES=()
RULES_TGT=()

# Optional singular arguments
# Output interface
[[ -n $OF ]] &&
	xIF="-i $OF" &&
	OF="-o $OF"

# Input interface (FORWARD chains only)
[[ -n $IF ]] &&
	xOF="-o $IF" &&
	IF="-i $IF"

# protocol
[[ -n $PROTOCOL ]] && PROTOCOL="-p $PROTOCOL"

# ctstate
[[ -n $CTSTATE ]] && CTSTATE="-m conntrack --ctstate $CTSTATE"

# Address restrictions
[[ -n $DEST ]] &&
	xSRC="-s $DEST" &&
	DEST="-d $DEST"

[[ -n $SRC ]] &&
	xDEST="-d $SRC" &&
	SRC="-s $SRC"

# Just specify destination port
# with respect to client
[[ -n $PORT ]] &&
dport="--dport $PORT" &&
xsport="--sport $PORT" &&
xdport= && sport=

# Specify source port and destination port
# OVERRIDES PORT
# with respect to client
[[ -n $DPORT ]] &&
	dport="--dport ${DPORT}" &&
	xsport="--sport ${DPORT}"
[[ -n $SPORT ]] &&
	xdport="--dport ${SPORT}" &&
	sport="--sport ${SPORT}"

# target (use default if unspecified)
[[ -z $TARGET ]] &&
	TARGET=JUMP[$DCHAIN]

# OUTPUT
RULES[0]="$DCHAIN $IF $OF $PROTOCOL ${SRC} ${DEST} $sport $dport"
RULES_TGT[0]="-j $TARGET"

# RETURN
RULES[1]="$CHAIN $xIF $xOF $PROTOCOL $CTSTATE ${xDEST} ${xSRC} $xsport $xdport"
RULES_TGT[1]="-j $TARGET"

# Execute function
$1
