#!/bin/bash

# Create final rule
ENV_FILE=`dirname "$(dirname \
					 "$(readlink -e "$0" )")"`/init.d/env
source "${ENV_FILE}" "$@" || exit 1

RULES=()
RULES_TGT=()

i=0;
for CHAIN in INPUT OUTPUT FORWARD;
do
	RULES[i]="$CHAIN"
	RULES_TGT[i]="-j ${FINAL_JUMP[$CHAIN]}"
  ((i++))
	RULES[i]="6 $CHAIN"
	RULES_TGT[i]="-j ${FINAL_JUMP[$CHAIN]}"
  ((i++))
done

$@
