#!/bin/bash

# This script configures a policy for the local interface.
# (Adaptable for any interface)

ENV_FILE=`dirname "$(dirname \
					 "$(readlink -e "$0" )")"`/init.d/env
source "${ENV_FILE}" "$@" || exit 1

# Empty arrays
RULES=()
RULES_TGT=()

i=0

for C in $CHAIN;
do
	RULES[$i]="$C -i $IF "
	RULES_TGT[$i]="-j $TARGET"
	((i++))
done

for C in $CHAIN_6;
do
	RULES[$i]="6 $C -i $IF_6 "
	RULES_TGT[$i]="-j $TARGET_6"
	((i++))
done

for C in $DCHAIN;
do
	RULES[$i]="$C -o $OF "
	RULES_TGT[$i]="-j $TARGET"
	((i++))
done


for C in $DCHAIN_6
do
	RULES[$i]="6 $C -o $OF_6 "
	RULES_TGT[$i]="-j $TARGET_6"
	((i++))
done

# Execute function
$1
