#!/bin/bash

# A template for creating init scripts for iptables.
ENV_FILE=`dirname "$(dirname \
					 "$(readlink -e "$0" )")"`/init.d/env
source "${ENV_FILE}" "$@" || exit 1

# Empty arrays
RULES=()
RULES_TGT=()

# Allow masquerading between interfaces.
# Remember to enable ip forwarding in the kernel with.
# `echo "1" > /proc/sys/net/ipv4/ip_forward`

# Examples..
# ${IPTABLES} -t nat -A POSTROUTING -o wlp3s0b1 -j MASQUERADE -m mark --mark 404
# ${IPTABLES} -t mangle -A PREROUTING -i enp12s0 -j MARK --set-mark 404
# ${FORWARD} -i enp12s0 -j ACCEPT

i=0
MASQ_IN="-t mangle -i ${IF} --set-mark"
MASQ_OUT="-t nat -o ${OF} -m mark --mark"
MASQ_IN_6="-t mangle -i ${IF_6} --set-mark"
MASQ_OUT_6="-t nat -o ${OF_6} -m mark --mark"

[[ -n $IF ]] &&
	RULES[$i]="PREROUTING ${MASQ_IN} $MARK" &&
	RULES_TGT[$i]="-j MARK" &&
	(( i++ ))

[[ -n $OF ]] &&
	RULES[$i]="POSTROUTING ${MASQ_OUT} $MARK" &&
	RULES_TGT[$i]="-j MASQUERADE" &&
	(( i++ ))

[[ -n $IF_6 ]] &&
	RULES[$i]="6 PREROUTING ${MASQ_IN_6} $MARK_6" &&
	RULES_TGT[$i]="-j MARK" &&
	(( i++ ))

[[ -n $OF_6 ]] &&
	RULES[$i]="6 POSTROUTING ${MASQ_OUT_6} $MARK_6" &&
	RULES_TGT[$i]="-j MASQUERADE" &&
	(( i++ ))

# Execute function
$1
