#!/bin/bash

# A template for creating init scripts for iptables.
ENV_FILE=`dirname "$(dirname \
					 "$(readlink -e "$0" )")"`/init.d/env
source "${ENV_FILE}" "$@" || exit 1

# Empty arrays
RULES=()
RULES_TGT=()

# Output interface
[[ -n $OF ]] &&
	xIF="-i $OF" &&
	OF="-o $OF"

# Input interface (FORWARD chains only)
[[ -n $IF ]] &&
	xOF="-o $IF" &&
	IF="-i $IF"

# Address restrictions
[[ -n $DEST ]] &&
	xSRC="-s $DEST" &&
	DEST="-d $DEST"

[[ -n $SRC ]] &&
	xDEST="-d $SRC" &&
	SRC="-s $SRC"

# target (use default if unspecified)
[[ -z $TARGET ]] &&
	TARGET=${JUMP[$DCHAIN]}

# protocol
PROTOCOL="-p icmp"

# OUTPUT
RULES[0]="$DCHAIN $IF $OF $PROTOCOL ${SRC} ${DEST} --icmp-type $ICMP_REQUEST"
RULES_TGT[0]="-j $TARGET"

# RETURN
RULES[1]="$CHAIN $xIF $xOF $PROTOCOL ${xDEST} ${xSRC} --icmp-type $ICMP_REPLY"
RULES_TGT[1]="-j $TARGET"

# Execute function
$1
