#!/bin/bash

# Creates the default policy

ENV_FILE=`dirname "$(dirname \
					 "$(readlink -e "$0" )")"`/init.d/env
source "${ENV_FILE}" "$@" || exit 1

# Empty arrays
RULES=()
RULES_TGT=()

i=0
# Only the filter table is valid for adjusting policy

for T in "${TABLE[@]}"; do
	for C in "${CHAIN[@]}"; do
		RULES[$i]="NIL ${IPTABLES} -w -t ${T} -P ${C} ${POLICY[${C}]}"
		RULES_TGT[$i]=""
		((i++))
	done
done

# IPv6
for T in "${TABLE_6[@]}"; do
	for C in "${CHAIN_6[@]}"; do
		RULES[$i]="6 NIL ${IPTABLES_6} -w -t ${T} -P ${C} ${POLICY_6[${C}]}"
		RULES_TGT[$i]=""
		((i++))
	done
done

# Log function not available
log() {
	echo "LOG FUNCTION NOT AVAILABLE" ; exit 1
}

status() {
	local T
	for T in "${TABLES[@]}"
	do
		echo -e "\nTable: ${T}"
		echo -e "\t${IPTABLES}"
		${IPTABLES} -t $T -nxvL | grep "policy"
		echo -e "\t${IPTABLES_6}"
		${IPTABLES_6} -t $T -nxvL | grep "policy"
	done
	}
# Execute function
$1
