#!/bin/bash

# Creates the default policy

ENV_FILE=`dirname "$(dirname \
					 "$(readlink -e "$0" )")"`/init.d/env
source "${ENV_FILE}" "$@" || exit 1

# Empty arrays
RULES=()
RULES_TGT=()

i=0
for T in "${TABLES[@]}"
do
	for C in "${DEFAULT_CHAINS[@]}"; do
		RULES[$i]="NIL ${IPTABLES} -w -t ${T} -P $C ${POLICY[${C}]}"
		RULES_TGT[$i]=""
		((i++))
		RULES[$i]="6 NIL ${IPTABLES_6} -w -t ${T} -P $C ${POLICY_6[${C}]}"
		RULES_TGT[$i]=""
		((i++))
	done
done

# Log function not available
log() {
	echo "LOG FUNCTION NOT AVAILABLE" ; exit 1
}

status() {
	local T
	for T in "${TABLES[@]}"
	do
		echo -e "\nTable: ${T}"
		echo -e "\t${IPTABLES}"
		${IPTABLES} -t $T -nxvL | grep "policy"
		echo -e "\t${IPTABLES_6}"
		${IPTABLES_6} -t $T -nxvL | grep "policy"
	done
	}
# Execute function
$1
